from .DialogueTemplate import DialogueTemplate
# from .InputMisheardDialogueTemplate import InputMisheardDialogueTemplate
# from .PromptDialogueTemplate import  PromptDialogueTemplate
# from .PumpingGeneralDialogueTemplate import PumpingGeneralDialogueTemplate
from .UnknownDialogueTemplate import UnknownDialogueTemplate

from .FeedbackDialogueTemplate import FeedbackDialogueTemplate
from .HintingDialogueTemplate import HintingDialogueTemplate
from .InputMisheardDialogueTemplate import InputMisheardDialogueTemplate
from .PromptDialogueTemplate import PromptDialogueTemplate
from .PumpingGeneralDialogueTemplate import PumpingGeneralDialogueTemplate
from .PumpingSpecificDialogueTemplate import PumpingSpecificDialogueTemplate
from .ORSENWelcomeDialogueTemplate import ORSENWelcomeDialogueTemplate


from .DialogueHistoryTemplate import DialogueHistoryTemplate

"""EDEN"""
from .CPumpingDialogueTemplate import CPumpingDialogueTemplate
from .DCorrectingDialogueTemplate import DCorrectingDialogueTemplate
from .DPraiseDialogueTemplate import DPraiseDialogueTemplate
from .DPumpingDialogueTemplate import DPumpingDialogueTemplate
from .ELabelDialogueTemplate import ELabelDialogueTemplate
from .EPumpingDialogueTemplate import EPumpingDialogueTemplate
from .EvaluationDialogueTemplate import EvaluationDialogueTemplate
from .RecollectionDialogueTemplate import RecollectionDialogueTemplate
from .EEndDialogueTemplate import EEndDialogueTemplate
from .EEmphasisDialogueTemplate import EEmphasisDialogueTemplate
from .EDENWelcomeDialogueTemplate import EDENWelcomeDialogueTemplate

