from .DialogueTemplate import DialogueTemplate
# from .InputMisheardDialogueTemplate import InputMisheardDialogueTemplate
# from .PromptDialogueTemplate import  PromptDialogueTemplate
# from .PumpingGeneralDialogueTemplate import PumpingGeneralDialogueTemplate
from .UnknownDialogueTemplate import UnknownDialogueTemplate

from .FeedbackDialogueTemplate import FeedbackDialogueTemplate
from .HintingDialogueTemplate import HintingDialogueTemplate
from .InputMisheardDialogueTemplate import InputMisheardDialogueTemplate
from .PromptDialogueTemplate import PromptDialogueTemplate
from .PumpingGeneralDialogueTemplate import PumpingGeneralDialogueTemplate
from .PumpingSpecificDialogueTemplate import PumpingSpecificDialogueTemplate
from .SuggestingDialogueTemplate import SuggestingDialogueTemplate

from .DialogueHistoryTemplate import DialogueHistoryTemplate


